login:
  oauth2_enabled:
    default: false
    client: true
  oauth2_client_id: ''
  oauth2_client_secret: ''
  oauth2_authorize_url: ''
  oauth2_token_url: ''
  oauth2_user_json_url: ''
  oauth2_json_user_id_path: ''
  oauth2_json_username_path: ''
  oauth2_json_name_path: ''
  oauth2_json_email_path: ''
  oauth2_email_verified: false
  oauth2_send_auth_header: true
  oauth2_force_email_domain: ''
  oauth2_override_username: false
  oauth2_store_username_in_title: false
  oauth2_debug_auth: false
  oauth2_button_title:
    default: 'with OAuth2'
    client: true
  oauth2_avatar_url_template: ''
